from django.core.management import BaseCommand
from feeds.models import Feed, Publisher

class Command(BaseCommand):
    # Show this when the user types help
    help = "Adds StartUp default feeds"

    def handle(self, *args, **options):
        initial_publishers = [
            {'name': 'Financial Times',
             'link': 'https://www.ft.com',
             'renowned': 3,
             'paywall': 'Y',
             'unique_article_id': 'guid',
             'img_scrape_urls': 'https://www.ft.com\nhttps://www.ft.com/world-uk\nhttps://www.ft.com/us\nhttps://www.ft.com/europe\nhttps://www.ft.com/news-feed'},
            {'name': 'The Economist',
             'link': 'http://www.economist.com',
             'renowned': 3,
             'paywall': 'Y',
             'unique_article_id': 'url',
             'img_scrape_urls': 'http://www.economist.com'},
            {'name': 'Al Jazeera',
             'link': 'https://www.aljazeera.com',
             'renowned': 1,
             'paywall': 'N',
             'unique_article_id': 'guid',
             'img_scrape_urls': 'https://www.aljazeera.com'},
            {'name': 'CNBC',
             'link': 'https://www.cnbc.com',
             'renowned': 1,
             'paywall': 'N',
             'unique_article_id': 'guid',
             'img_scrape_urls': 'https://www.cnbc.com/economy/\nhttps://www.cnbc.com/latest/\nhttps://www.cnbc.com'},
            {'name': 'Risk.net',
             'link': 'https://www.risk.net',
             'renowned': 1,
             'paywall': 'Y',
             'unique_article_id': 'url',
             'img_scrape_urls': 'https://www.risk.net'},
            {'name': 'Reuters',
             'link': 'https://www.reuters.com',
             'renowned': 1,
             'paywall': 'N',
             'unique_article_id': 'url',
             'img_scrape_urls': 'https://www.reuters.com'},
            {'name': 'Deutsche Welle',
             'link': 'https://www.dw.com',
             'renowned': 1,
             'paywall': 'N',
             'unique_article_id': 'title',
             'img_scrape_urls': 'https://www.dw.com\nhttps://www.dw.com/en/headlines/headlines-en'},
            {'name': 'Bloomberg',
             'link': 'https://www.bloomberg.com',
             'renowned': 2,
             'paywall': 'Y',
             'unique_article_id': 'url',
             'img_scrape_urls': None}
        ]

        for publisher in initial_publishers:
            Publisher(**publisher).save()


        initial_feeds = [
            {'name': 'Financial Times - International',
             'publisher': Publisher.objects.get(name='Financial Times'),
             'url': 'https://www.ft.com/rss/home/international',
             'active': True,
             'feed_ordering': 'r',
             'full_text_fetch': 'Y',
             'display_section': 'main',
             'importance': 2},
            {'name': 'Financial Times - Markets',
             'publisher': Publisher.objects.get(name='Financial Times'),
             'url': 'https://www.ft.com/markets?format=rss',
             'active': True,
             'feed_ordering': 'r',
             'full_text_fetch': 'Y',
             'display_section': 'main',
             'importance': 0,
             'genre': 'finance'},
            {'name': 'Financial Times - US',
             'publisher': Publisher.objects.get(name='Financial Times'),
             'url': 'https://www.ft.com/us?format=rss',
             'active': True,
             'feed_ordering': 'r',
             'full_text_fetch': 'Y',
             'display_section': 'main',
             'importance': 0,
             'genre': 'us'},
            {'name': 'Financial Times - UK',
             'publisher': Publisher.objects.get(name='Financial Times'),
             'url': 'https://www.ft.com/world-uk?format=rss',
             'active': True,
             'feed_ordering': 'r',
             'full_text_fetch': 'Y',
             'display_section': 'main',
             'importance': 0,
             'genre': 'europe'},
            {'name': 'Financial Times - Europe',
             'publisher': Publisher.objects.get(name='Financial Times'),
             'url': 'https://www.ft.com/europe?format=rss',
             'active': True,
             'feed_ordering': 'r',
             'full_text_fetch': 'Y',
             'display_section': 'main',
             'importance': 0,
             'genre': 'europe'},
            {'name': 'CNBC - Markets',
             'publisher': Publisher.objects.get(name='CNBC'),
             'url': 'https://search.cnbc.com/rs/search/combinedcms/view.xml?partnerId=wrss01&id=20910258',
             'active': False,
             'feed_ordering': 'r',
             'full_text_fetch': 'Y',
             'display_section': 'main',
             'importance': 1,
             'genre': 'finance'},
            {'name': 'Reuters - Next',
             'publisher': Publisher.objects.get(name='Reuters'),
             'url': 'http://FEED-CREATOR.local/extract.php?url=https%3A%2F%2Fwww.reuters.com%2Fworld%2Freuters-next%2F&in_id_or_class=content-layout__item__SC_GG&max=10&order=document&guid=0&strip=.label__label__f9Hew%2C.events__data__18XBG&keep_qs_params=',
             'active': True,
             'feed_ordering': 'r',
             'full_text_fetch': 'Y',
             'display_section': 'main',
             'importance': 1,
             'genre': 'finance'},
            {'name': 'Reuters - Markets',
             'publisher': Publisher.objects.get(name='Reuters'),
             'url': 'http://FEED-CREATOR.local/extract.php?url=https%3A%2F%2Fwww.reuters.com%2Fmarkets%2Fmacromatters%2F&in_id_or_class=content-layout__item__SC_GG&max=15&order=document&guid=0&strip=.label__label__f9Hew%2C.events__data__18XBG%2C.media-story-card__placement-container__1R55-&keep_qs_params=',
             'active': True,
             'feed_ordering': 'r',
             'full_text_fetch': 'Y',
             'display_section': 'main',
             'importance': 1,
             'genre': 'finance'},
            {'name': 'Risk.net',
             'publisher': Publisher.objects.get(name='Risk.net'),
             'url': 'http://www.risk.net/feeds/rss/',
             'active': True,
             'feed_ordering': 'r',
             'full_text_fetch': 'Y',
             'display_section': 'main',
             'importance': 1,
             'genre': 'finance'},
            {'name': 'CNBC - Top',
             'publisher': Publisher.objects.get(name='CNBC'),
             'url': 'https://search.cnbc.com/rs/search/combinedcms/view.xml?partnerId=wrss01&id=100003114',
             'active': False,
             'feed_ordering': 'r',
             'full_text_fetch': 'Y',
             'display_section': 'main',
             'importance': 1,
             'genre': 'finance'},
            {'name': 'Al Jazeera',
             'publisher': Publisher.objects.get(name='Al Jazeera'),
             'url': 'https://www.aljazeera.com/xml/rss/all.xml',
             'active': True,
             'feed_ordering': 'r',
             'full_text_fetch': 'Y',
             'display_section': 'main',
             'importance': 2},
            {'name': 'Detsche Welle - Top',
             'publisher': Publisher.objects.get(name='Deutsche Welle'),
             'url': 'http://rss.dw.com/rdf/rss-en-all',
             'active': True,
             'feed_ordering': 'r',
             'full_text_fetch': 'Y',
             'display_section': 'main',
             'importance': 2,
             'genre': 'world'},
            {'name': 'Bloomberg - Markets',
             'publisher': Publisher.objects.get(name='Bloomberg'),
             'url': 'https://feeds.bloomberg.com/markets/news.rss',
             'active': True,
             'feed_ordering': 'r',
             'full_text_fetch': 'N',
             'display_section': 'main',
             'importance': 2,
             'genre': 'finance'},
            {'name': 'Bloomberg - Politics',
             'publisher': Publisher.objects.get(name='Bloomberg'),
             'url': 'https://feeds.bloomberg.com/politics/news.rss',
             'active': True,
             'feed_ordering': 'r',
             'full_text_fetch': 'N',
             'display_section': 'main',
             'importance': 2,
             'genre': 'global'},
            {'name': 'Economist - Top News',
             'publisher': Publisher.objects.get(name='The Economist'),
             'url': 'http://FEED-CREATOR.local/mergefeeds.php?url%5B0%5D=https%3A%2F%2Fwww.economist.com%2Fbriefing%2Frss.xml&url%5B1%5D=https%3A%2F%2Fwww.economist.com%2Ffinance-and-economics%2Frss.xml&max=5&order=date',
             'active': True,
             'feed_ordering': 'r',
             'full_text_fetch': 'Y',
             'display_section': 'main',
             'importance': 0,
             'genre': 'finance'},
            {'name': 'The Economist - Countries',
             'publisher': Publisher.objects.get(name='The Economist'),
             'url': 'http://FEED-CREATOR.local/mergefeeds.php?url%5B0%5D=https%3A%2F%2Fwww.economist.com%2Feurope%2Frss.xml&url%5B1%5D=https%3A%2F%2Fwww.economist.com%2Finternational%2Frss.xml&url%5B2%5D=https%3A%2F%2Fwww.economist.com%2Funited-states%2Frss.xml&url%5B3%5D=https%3A%2F%2Fwww.economist.com%2Fthe-americas%2Frss.xml&url%5B4%5D=https%3A%2F%2Fwww.economist.com%2Fmiddle-east-and-africa%2Frss.xml&url%5B5%5D=https%3A%2F%2Fwww.economist.com%2Fasia%2Frss.xml&url%5B6%5D=https%3A%2F%2Fwww.economist.com%2Fchina%2Frss.xml&url%5B7%5D=https%3A%2F%2Fwww.economist.com%2Fbritain%2Frss.xml&max=12&order=date',
             'active': True,
             'feed_ordering': 'r',
             'full_text_fetch': 'Y',
             'display_section': 'main',
             'importance': 0,
             'genre': 'world'}
        ]


        for feed in initial_feeds:
            Feed(**feed).save()
