name: Production Deployment
on:
  push:
    branches:
      - master
      - main

jobs:

  autotag:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        id: checkout
        with:
          ref: ${{ github.event.pull_request.merge_commit_sha }}
          fetch-depth: '0'

      - name: Bump version and push tag
        id: tagger
        uses: anothrNick/github-tag-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    outputs:
      out_tag: ${{ steps.tagger.outputs.tag }}
      out_new_tag: ${{ steps.tagger.outputs.new_tag }}
      out_part: ${{ steps.tagger.outputs.part }}
